<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

# 最终结果是类 ClassLoader 的实例化对象
# 类 ClassLoader 的主要作用是什么呢？

return ComposerAutoloaderInit76b982e74f91b60dd43bcc25083d2d45::getLoader();
